stages:
  - build
  - test
  - deploy


build-job:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:8.0
  script:
    - echo "Устанавливаем библиотеки"
    - dotnet restore
    - echo "Компилируем проект"
    - dotnet build --no-restore -c Release

test-job:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:8.0
  script:
    - echo "Запускаем тесты"
    - dotnet test --verbosity normal
  dependencies:
    - build-job
