stages:
  - build
  - test


build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:8.0
  script:
    - echo "Устанавливаем библиотеки"
    - dotnet restore
    - echo "Компилируем проект"
    - dotnet build --no-restore -c Release
