name: Build and Test project

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Получение исходного кода
        uses: actions/checkout@v3

      - name: Установка .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Установка библиотек
        run: dotnet restore

      - name: Сборка проекта
        run: dotnet build --no-restore

      - name: Сохранение объектов сборки
        uses: actions/upload-artifacts@v3
        with:
          name: build-output
          paths: |
            - '**/bin'
            - '**/obj'

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Получение исходного кода
        uses: actions/checkout@v3

      - name: Установка .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Скачивание объектов сборки
        uses: actions/download-artifacts@v3
        with:
          name: build-output
          path: build-artifacts

      - name: Сборка проекта
        run: dotnet test --no-build --verbosity normal
